### PR TITLE
Added Ryukyuan languages

### PR DESCRIPTION
**Pull request by kuragehimekurara1**
Ryukyuan languages have been added

### CODE REVIEW

**Comment by cy33hc** [comment]
@kuragehimekurara1 Is this a variant of Japanese or Korean? I need to know, because I need to load the correct font file that contains those symbols

**Comment by kuragehimekurara1** [comment]
I think this is Japanese because it is a language spoken in some parts of Japan

**Comment by cy33hc** [comment]
@kuragehimekurara1 I've released version 1.4.9 with Ryukyuan language.

**Comment by kuragehimekurara1** [comment]
Thank you for the release!

**Pull request merged**
